import '@/app/globals.css';
import NavigationBar from '@/app/_components/navigation/NavigationBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        <main className="pt-24">{children}</main>
        {/* Footer */}
      </body>
    </html>
  );
}
