import Navbar from '@/app/_components/Navbar';
import '@/app/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { name: 'Reserveren', href: '/reserveren' },
  { name: 'Wie', href: '/wie' },
  { name: 'Activiteiten', href: '/activiteiten' },
  { name: 'Plattegrond', href: '/plattegrond' },
  { name: 'Contact', href: '/contact' },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar menuItems={menuItems} />
        <main>{children}</main>
        {/* Footer */}
      </body>
    </html>
  );
}
